FROM node:lts-alpine AS build

WORKDIR /app

COPY ./package.json ./

RUN npm install 

COPY . .

ENV VITE_API_URL=http://localhost/api

RUN npm run build

CMD [ "npm", "run" , "preview" ]

# Étape de déploiement
FROM nginx:latest
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

