version: '3.8'

services:
  nginx_prod:
    container_name: nginx_prod
    depends_on:
      - api_prod
      - client_prod
      - db_prod
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"

  api_prod:
    container_name: api_prod
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.prod
      context: ./api
    environment:
      - SMTP_HOST=mailhog_prod
      - SMTP_PORT=1025

  db_prod:
    container_name: db_prod
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ecoursa_prod
    ports:
      - 543:5432
    volumes:
      - pgdata_prod:/var/lib/postgresql/data  

  mailhog_prod:
    container_name: mailhog_prod
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - 1026:1025
      - 8026:8025  
    environment:
      MH_STORAGE: memory 
    volumes:
      - maildir_prod:/tmp   

  client_prod:
    container_name: client_prod
    stdin_open: true
    environment:
      WATCHPACK_POLLING: "true"
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.prod
      context: ./client 

volumes:
  pgdata_prod: {}
  maildir_prod: {}
