version: '3.8'

services:
  nginx_dev:
    container_name: nginx_dev
    depends_on:
      - api_dev
      - client_dev
      - db_dev
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:81'

  api_dev:
    container_name: api_dev
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app 
    environment:
      - SMTP_HOST=mailhog_dev
      - SMTP_PORT=1025

  db_dev:
    container_name: db_dev
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ecoursa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailhog_dev:
    container_name: mailhog_dev
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp   

  client_dev:
    container_name: client_dev
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app   
    environment:
    - WDS_SOCKET_HOST=127.0.0.1 
    - CHOKIDAR_USEPOLLING=true
    - WATCHPACK_POLLING=true
volumes:
  pgdata: {}
  maildir: {}
